# Generated by Django 6.0 on 2025-12-21 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
